version: "3.8"
services:
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo-grs
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_DB: $MONGO_DB
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  mongo-express:
    image: mongo-express
    container_name: lgp-mongo-express
    restart: always
    ports:
      - $ME_CONFIG_PORT:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongo:27017